ログイン機能実装
yujicosao/docker-laravel-sample-project pull request #6
Opened 2021-09-06 02:02 UTC by yujicosao

全ページヘッダーにログイン・ログアウトボタン設置

参考：
https://qiita.com/_Mizuki/items/eb8c627c363aa1396342
https://memocarilog.info/php-mysql/8749#article01

2021-09-10 02:58 UTC, tatsukoni requested changes
レビューしてみました！

2021-09-10 02:58 UTC, tatsukoni commented on backend/resources/views/base.blade.php
> +    {{ Auth::user()->name }}様：ログイン中です
ユーザ名は、バックエンド側から返却する形にしても良いかもしれないですね!
(OurPhotoでは、そのような実装になっているケースが多いかと思います)

2021-09-10 02:58 UTC, tatsukoni commented on backend/app/Providers/RouteServiceProvider.php
> +    public const HOME = '/admin-news';
定数については、もしこのファイル内だけで使う場合は`private const`として定義しても良いかもです!

2021-09-11 06:33 UTC, yujicosao commented on backend/app/Providers/RouteServiceProvider.php
> +    public const HOME = '/admin-news';
おそらくpublicで使う定数なのかと思います。
`private const HOME = '/admin-news';`
で試してみたところ、
`Cannot access private constant App\Providers\RouteServiceProvider::HOME`
こんな感じで怒られてしまいました。

2021-09-11 06:36 UTC, yujicosao commented on backend/resources/views/base.blade.php
> +    {{ Auth::user()->name }}様：ログイン中です
なるほどですね！

> バックエンド側から返却

というのは例えば、
baldeに書いていた下記のコードを
`Auth::user()->name`
controller側で
`$current_user = Auth::user()->name;`
このように書いて、
blade側では
{{ $current_user }}
こう書く、と言うことでしょうか？

2021-09-17 00:08 UTC, tatsukoni commented on backend/app/Providers/RouteServiceProvider.php
> +    public const HOME = '/admin-news';
なるほど、、
内部的にpublicで使っているんですかね。。
では、`public`で良いかと思います！:pray:

2021-09-17 00:09 UTC, tatsukoni commented on backend/resources/views/base.blade.php
> +    {{ Auth::user()->name }}様：ログイン中です
はい、記載頂いた形で大丈夫です！

2021-09-26 12:06 UTC, merged